# Generated by Django 5.1.3 on 2024-11-16 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='landmark',
            field=models.TextField(blank=True, max_length=300),
        ),
    ]
