# Generated by Django 5.1.3 on 2024-11-27 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_size_product_productvariant'),
        ('order', '0002_alter_cartitem_size'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Size',
        ),
    ]
