# Generated by Django 5.1.3 on 2024-11-17 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_product_average_rating_productreview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='average_rating',
        ),
        migrations.DeleteModel(
            name='ProductReview',
        ),
    ]
