# Generated by Django 5.1.3 on 2024-11-27 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_delete_size'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductVariant',
        ),
    ]
