# Generated by Django 5.1.3 on 2024-11-22 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_product_category_delete_subcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivereditem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='delivereditem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='order',
        ),
        migrations.RemoveField(
            model_name='shipping',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='shoppingcart',
            name='user',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
        migrations.DeleteModel(
            name='DeliveredItem',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Shipping',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
        migrations.DeleteModel(
            name='ShoppingCart',
        ),
    ]
