# Generated by Django 5.1.3 on 2024-11-17 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_delete_shipping'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_method', models.CharField(max_length=255)),
                ('shipping_status', models.CharField(default='Not Shipped', max_length=50)),
                ('tracking_number', models.CharField(blank=True, max_length=255, null=True)),
                ('shipping_date', models.DateTimeField(blank=True, null=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shipping', to='base.order')),
            ],
        ),
    ]
